### ISSUE TITLE
porblem in vendor\laurentesc\laravel-subdomain-localization\src\Router.php

### ISSUE THREAD

**Issue by nirlewin** [LaurentEsc/Laravel-Subdomain-Localization#1]
Hello,

There is a huge problem in the file vendor\laurentesc\laravel-subdomain-localization\src\Router.php

In this variable $parsed_url['host'] you supporting only the exaple.com type. There is no support of types of sub-domain like example.com.mx or sub.exaple.com at all.

**Comment by LaurentEsc** [comment]
Hi nirlewin,

Thank you for reporting this issue. I was already aware about this but now I took the time to fix the problem. Now the domain is part of the package configuration and can be set to whatever you want. I will update the documentation tomorrow. It would be nice if you can test and confirm it solves your problem. Just update the package and add the domain to the package config (See https://github.com/LaurentEsc/Laravel-Subdomain-Localization/blob/master/config/config.php).
