### ISSUE TITLE
Error when using url route as

### ISSUE THREAD

**Issue by Xoce51** [LaurentEsc/Laravel-Subdomain-Localization#2]
Hi,
Thank you for this module, but I facing an issue.
When I name my route like this:

``` PHP
Route::get('/', [
        'uses' => 'PageController@index',
        'as'   => 'page.index',
    ]);
```

The module try to translate the url with the 'as' path which gives to me an errors because it's returning an array.
The error is line 219 from Router.php on the ltrim function (get an array expected string).

I'm trying to debug this but as I'm newbie with laravel I can't figure out how app()['translator'] works

Any idea to make it working with custom route name ?

**Comment by LaurentEsc** [comment]
Hi Xoce51,

thank you for reporting, I will take a look.

**Comment by LaurentEsc** [comment]
I'm not sure to understand your issue. Can you please provide the error trace?
Which routing function are you using to translate the URL ?

**Comment by Xoce51** [comment]
I was using this function: 

``` PHP
Router::getCurrentVersions()
```

after some debugging, I saw that's I must have entries within 
`
resources/lang/[lang]/routes.php
`
to use this function, is-it correct ?

I'm sorry I haven't any stacktrace because I temporarly desactivate the module.

**Comment by LaurentEsc** [comment]
Yes that's right you have to use language files in `resources/lang` to translate your URLs.

Here is an implementation example:

**Language files**

``` PHP
# resources/lang/en/routing.php

return [
    'welcome' => 'welcome'
];
```

``` PHP
# resources/lang/de/routing.php

return [
    'welcome' => 'wilkommen'
];
```

``` PHP
# resources/lang/fr/routing.php

return [
    'welcome' => 'bienvenue'
];
```

``` PHP
# resources/lang/en/global.php

return [
    'title' => 'Welcome to the English version',
    'text' => 'Text in English ... bla bla bla',
    'language.en' => 'English',
    'language.de' => 'German',
    'language.fr' => 'French',
];
```

``` PHP
# resources/lang/de/global.php

return [
    'title' => 'Willkommen in der Englische Version',
    'text' => 'Text auf Deutsch ... bla bla bla',
    'language.en' => 'Englisch',
    'language.de' => 'Deutsch',
    'language.fr' => 'Französisch',
];
```

``` PHP
# resources/lang/fr/global.php

return [
    'title' => 'Bienvenue en version francaise',
    'text' => 'Texte en Francais ... bla bla bla',
    'language.en' => 'Anglais',
    'language.de' => 'Allemand',
    'language.fr' => 'Francais',
];
```

**Routes**

``` PHP
# app/Http/routes.php

Route::get(Router::resolve('routing.welcome'), 'HomeController@index');
```

**Controller**

``` PHP
# app/Http/Controllers/HomeController.php

namespace App\Http\Controllers;

class HomeController extends Controller {

    public function index()
    {
        return view('welcome');
    }

}
```

**View**

``` PHP
# rerources/views/welcome.blade.php

<h1>{{ Lang::get('global.title') }}</h1>
<p>{{ Lang::get('global.text') }}</p>

<ul>
@foreach(Router::getCurrentVersions() as $locale => $url)
    <li>
        <a href="{{ $url }}">{{ Lang::get('global.language.' . $locale) }}</a>
    </li>
@endforeach
</ul>
```

**HTML output**

And here is the HTML output you should have while visiting http://en.yourdomain.com/welcome:

``` HTML
<h1>Welcome to the English version</h1>
<p>Text in English ... bla bla bla</p>

<ul>
    <li>
        <a href="http://de.yourdomain.com/wilkommen">German</a>
    </li>
    <li>
        <a href="http://fr.yourdomain.com/bienvenue">French</a>
    </li>
</ul>
```

Please let me know if this helps solving your problem.

**Comment by Xoce51** [comment]
Ok, thank you for these precision, my fault sorry I misused the program. I'm gonna take a look at this in a few days. Thank you again.
