### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::share()

### ISSUE THREAD

**Issue by wlepinski** [LaurentEsc/Laravel-Subdomain-Localization#6]
The method `::share()` is now deprecated and you should use the `->singleton()` method instead.

```php
$container->singleton('foo', function () {
    return 'foo';
});
```

**Comment by LaurentEsc** [comment]
I've juste merged a PR that should add support for Laravel 5.4+ by fixing this problem. Thanks for reporting and sorry for the late answer.
